title: üçì samit
author: "machine learning engineer"
email: "samitmohan@gmail.com"
description: my home on the internet
baseurl: ""
url: "https://samitmohan.github.io"

theme: minima
future: true
show_excerpts: false

header_pages:
  - about.markdown
  - projects.markdown
  - search.html


markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
