title: ğŸ“ samit
author:
  "machine learning engineer"
email: "samitmohan@gmail.com"
description: my home on the internet
baseurl: ""
url: "https://samitmohan.github.io"
github_username: samitmohan
twitter_username: samitmohan
theme: minima
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  math_engine: katex
